### 단일 조회
GET {{host}}/api/members/5
Content-type: application/json

### 멤버 생성
POST {{host}}/api/members
Content-type: application/json

{
  "email": "hi@abc.com",
  "name": "hi"
}

### 멤버 업데이트
PUT {{host}}/api/members/5
Content-type: application/json

{
  "name": "new-hi"
}

### 페이지 조회
GET {{host}}/api/members?page=0&size=2
Content-Type: application/json